FROM node:dubnium
WORKDIR /usr/src

COPY package-lock.json package.json ./
RUN npm install

ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_MESSAGING_ID
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_AUTH0_CLIENT_ID
ARG REACT_APP_AUTH0_CALLBACK_URL

COPY . .
RUN npm run build && mv build /public
